# Generated by Django 5.0.6 on 2024-05-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0002_remove_vendormodel_id_alter_vendormodel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderModel',
            fields=[
                ('po_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_data', models.DateTimeField(blank=True, null=True)),
                ('items', models.JSONField()),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('quality_rating', models.FloatField(blank=True, null=True)),
                ('issue_date', models.DateTimeField()),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendormodel')),
            ],
        ),
    ]
