# Generated by Django 5.0.6 on 2024-05-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseordermodel',
            name='delivered_data',
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
