# Generated by Django 5.0.6 on 2024-05-11 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_remove_purchaseordermodel_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
